'use strict';

try{
    let x = 10;
}
catch (error){
    console.log(error);
}

finally{
        console.log('Termina la revisi√≥n de errores');
}

console.log('Continuamos...');
